### ISSUE TITLE
AssertionError("TYPE_ARRAY requires the items attribute")

### ISSUE THREAD

**Issue by ghost** [glowka/drf-yasg-json-api#3]
Hello, I am receiving this error after running the server although there are no custom swagger_auto_schema declared in the API.
```
raise AssertionError("TYPE_ARRAY requires the items attribute")
AssertionError: TYPE_ARRAY requires the items attribute
```
Any help on this is appreciated.

**Comment by glowka** [comment]
Hi, this error can be both fault of view (and its serializer) that does not fully adhere to some JSON API assumptions or bug of this library. I know that those `drf-yasg` assertion are sometimes not very descriptive, so it would be nice do a bit of investigation.

My way to find the view triggering the error is to comment out half of the urls and check if the error is still present. If it is, then comment out the half of the remaining urls. If not, uncomment half of the previously commented urls. Repeat the steps until you find the single view triggering error.

**Once you do find relevant view, can you post it here, along with its serializer?**

BTW I just thought it would be nice to get much more descriptive assertions, I'll consider reporting it as feature proposal to `drf-yasg`

**Comment by ghost** [comment]
Hi, thanks for the response following is one of the many views which are creating problems, can you please suggest me a better way of writing this, I don't think the error is because of the serializer. 

```
class CurrentUserView(APIView):
    def get(self, request):
        serializer = UserSerializer(request.user)
        return Response(serializer.data)
```

**Comment by glowka** [comment]
So `drf-yasg` expects you to expose serializer using `get_serializer` method.

This is works out of the box if you use `GenericAPIView`, but you can also keep using `ApiView` but simply transform your view to:

```
class CurrentUserView(APIView):
    def get_serializer(*args, **kwargs):
        return UserSerializer(*args, **kwargs)

    def get(self, request):
        serializer = self.get_serializer(request.user)
        return Response(serializer.data)
```

**Comment by ghost** [comment]
Thanks, I really appreciate the guidance and closing the issue.
