### ISSUE TITLE
Incorrect schema for non-model viewset list

### ISSUE THREAD

**Issue by art-vasilyev** [glowka/drf-yasg-json-api#5]
drf-yasg-json-api generates incorrect schema for non-model views (rest_framework.viewsets.ViewSet). Here is a test that shows it:
```
diff --git a/tests/test_schema/test_get.py b/tests/test_schema/test_get.py
index c850bdf..1438584 100644
--- a/tests/test_schema/test_get.py
+++ b/tests/test_schema/test_get.py
@@ -7,10 +7,12 @@ import drf_yasg.inspectors
 from django.conf.urls import url
 from drf_yasg import openapi
 from drf_yasg.generators import OpenAPISchemaGenerator
+from drf_yasg.utils import swagger_auto_schema
 from rest_framework import mixins
 from rest_framework import routers
 from rest_framework import views
 from rest_framework import viewsets
+from rest_framework.response import Response
 from rest_framework_json_api import django_filters
 from rest_framework_json_api import filters
 from rest_framework_json_api import pagination
@@ -242,3 +244,31 @@ def test_get__filter():
 
     request_parameters_schema = swagger['paths']['/projects/']['get']['parameters']
     assert request_parameters_schema[0]['name'] == 'filter[archived]'
+
+
+def test_get_nonmodel_many():
+    class ProjectSerializer(serializers.Serializer):
+        pk = serializers.IntegerField()
+        name = serializers.CharField()
+
+    class ProjectViewSet(viewsets.ViewSet):
+        renderer_classes = [renderers.JSONRenderer]
+        parser_classes = [parsers.JSONParser]
+        swagger_schema = base.BasicSwaggerAutoSchema
+        resource_name = 'projects'
+
+        @swagger_auto_schema(responses={200: ProjectSerializer(many=True)})
+        def list(self, request):
+            projects = [{'pk': 1, 'name': 'test'}]
+            serializer = ProjectSerializer(data=projects, many=True)
+            return Response(serializer.data)
+
+    router = routers.DefaultRouter()
+    router.register(r'projects', ProjectViewSet, **compatibility._basename_or_base_name('projects'))
+
+    generator = OpenAPISchemaGenerator(info=openapi.Info(title="", default_version=""), patterns=router.urls)
+
+    swagger = generator.get_schema(None, True)
+
+    response_schema = swagger['paths']['/projects/']['get']['responses']['200']['schema']
+    assert response_schema.type != 'array'

```

It works fine for single item view, but for list view it generates non-json-api schema:
```
[
  {
    "id": "integer",
    "name": "string"
  }
]
```

**Comment by glowka** [comment]
Hi, thanks for your report and detailed description.

From my point of view `rest_framework_json_api` is primarly to be used with models, most of the features require using models, especially all relationship features. Clear differentiation between attributes and relationships as well as taking advantage of including many related objects in one response are the fields in which JSON API shines the brightest. This is as well main focus of `drf-yasg-json-api`.

Of course, this does not cover all possible needs and scenarios, each one is worth considering for being supported by `drf-yasg-json-api`, so my question is: **what is your use case? What made you abandon model-driven views?**

Regardless of the anwer (which is crucial) I would adjust your snippet this way:
```
def test_get_nonmodel_many():
    class ProjectSerializer(serializers.Serializer):
        id = serializers.IntegerField()
        name = serializers.CharField()

    class ProjectViewSet(viewsets.ViewSet):
        renderer_classes = [renderers.JSONRenderer]
        parser_classes = [parsers.JSONParser]
        swagger_schema = base.BasicSwaggerAutoSchema
        resource_name = 'projects'
        serializer_class = ProjectSerializer

        def get_serializer(self, *args, **kwargs):
            return self.serializer_class(*args, **kwargs)

        def list(self, request):
            projects = [{'id': 1, 'name': 'test'}]
            serializer = self.get_serializer(data=projects, many=True)
            return Response(serializer.data)
    ...
```
As described in https://github.com/glowka/drf-yasg-json-api#data-field-with-id-type-relationships-attributes-structure, 
1. _Schema based on view's main serializer_ – `drf-yasg-json-api` infers format of the response from the view's serializer which in case of `GenericAPIView` is returned at `get_serializer`, if you don't use it, you need to define it manually as done above. 
2. `Id` is currently _`id` field or other serializer field that matches the model `pk` field_ –  in this case it must be `id` field as there is no model.

**Comment by art-vasilyev** [comment]
Thanks for the detailed answer, it solves my issue. I need to use json-api for compatibility with other services, but actually service just proxies requests to another API, so I don't have models. Thanks. closing this issue
