### ISSUE TITLE
Compatibility with django-rest-framework-json-api 5.0

### ISSUE THREAD

**Issue by nikosmichas** [glowka/drf-yasg-json-api#8]
Hello,
I am trying to update a project in new versions of Django, DRF etc, and I am having some issues with `drf-yasg-json-api` compatibility with new version of `django-rest-framework-json-api`.
I will try to fix this in a fork. Can I submit a PR for this?
Thanks

**Comment by glowka** [comment]
Hi! Yeah, definitely. PR adding compatibility to new-released `django-rest-framework-json-api` version 5.0 will be highly welcome.
